name: dig_text_similarity
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.6
  - faiss-cpu=1.4.0
  - pip:
    - happybase>=1.1.0
    - numpy
    - tensorflow_hub
    - Flask
    - Flask-API
    - flask-cors
    - requests
    - tensorflow
    - elasticsearch>=6.3.1
    - pandas
    - ipykernel
    - jupyter
    - dash==0.27.0
    - dash-html-components==0.12.0
    - dash-core-components==0.28.0 
